/**
 * Central set registry.
 * Add new sets here — both tcgdex.js and achievements.js consume this list.
 *
 * rarityRanges: { [rarityName]: [minLocalId, maxLocalId] } (inclusive)
 * rarityTotals: card count per rarity (used as fallback when set isn't loaded yet)
 */
export const SETS = [
  {
    id: 'base1',
    name: 'Base Set',
    series: 'Base',
    year: '1999',
    totalCards: 102,
    symbol: '◆',
    accentColor: '#e63946',
    rarityRanges: {
      'Rare Holo': [1, 16],
      'Rare':      [17, 32],
      'Uncommon':  [33, 64],
      'Common':    [65, 102],
    },
    rarityTotals: {
      'Rare Holo': 16,
      'Rare':      16,
      'Uncommon':  32,
      'Common':    38,
    },
  },
  {
    id: 'base2',
    name: 'Jungle',
    series: 'Base',
    year: '1999',
    totalCards: 64,
    symbol: '🌴',
    accentColor: '#2d6a4f',
    rarityRanges: {
      'Rare Holo': [1, 16],
      'Rare':      [17, 32],
      'Uncommon':  [33, 48],
      'Common':    [49, 64],
    },
    rarityTotals: {
      'Rare Holo': 16,
      'Rare':      16,
      'Uncommon':  16,
      'Common':    16,
    },
  },
  {
    id: 'base3',
    name: 'Fossil',
    series: 'Base',
    year: '1999',
    totalCards: 62,
    symbol: '◈',
    accentColor: '#78716c',
    rarityRanges: {
      'Rare Holo': [1, 16],
      'Rare':      [17, 32],
      'Uncommon':  [33, 48],
      'Common':    [49, 62],
    },
    rarityTotals: {
      'Rare Holo': 16,
      'Rare':      16,
      'Uncommon':  16,
      'Common':    14,
    },
  },
  {
    id: 'base4',
    name: 'Base Set 2',
    series: 'Base',
    year: '2000',
    totalCards: 130,
    symbol: '◉',
    accentColor: '#7c3aed',
    rarityRanges: {
      'Rare Holo': [1, 28],
      'Rare':      [29, 56],
      'Uncommon':  [57, 90],
      'Common':    [91, 130],
    },
    rarityTotals: {
      'Rare Holo': 28,
      'Rare':      28,
      'Uncommon':  34,
      'Common':    40,
    },
  },
  {
    id: 'base5',
    name: 'Team Rocket',
    series: 'Base',
    year: '2000',
    totalCards: 82, // card 83 (Dark Raichu) is a secret rare – not in official count
    symbol: 'R',
    accentColor: '#dc2626',
    rarityRanges: {
      'Rare Holo':   [1,  16],
      'Rare':        [17, 32],
      'Uncommon':    [33, 56],
      'Common':      [57, 82],
      'Secret Rare': [83, 83],
    },
    rarityTotals: {
      'Rare Holo':   16,
      'Rare':        16,
      'Uncommon':    24,
      'Common':      26,
      'Secret Rare': 1,
    },
  },
  // ─── Gym Series ──────────────────────────────────────────────────────────
  {
    id: 'gym1',
    name: 'Gym Heroes',
    series: 'Base',
    year: '2000',
    totalCards: 132,
    symbol: '⊙',
    accentColor: '#f59e0b',
    rarityRanges: {
      // tcgdex labels cards 1-34 as Rare Holo; no separate Rare section
      'Rare Holo': [1, 34],
      'Uncommon':  [35, 88],
      'Common':    [89, 132],
    },
    rarityTotals: { 'Rare Holo': 34, 'Uncommon': 54, 'Common': 44 },
  },
  {
    id: 'gym2',
    name: 'Gym Challenge',
    series: 'Base',
    year: '2000',
    totalCards: 132,
    symbol: '⊕',
    accentColor: '#16a34a',
    rarityRanges: {
      'Rare Holo': [1, 20],
      'Rare':      [21, 30],
      'Uncommon':  [31, 59],
      'Common':    [60, 132],
    },
    rarityTotals: { 'Rare Holo': 20, 'Rare': 10, 'Uncommon': 29, 'Common': 73 },
  },
  // ─── Neo Series ──────────────────────────────────────────────────────────
  {
    id: 'neo1',
    name: 'Neo Genesis',
    series: 'Neo',
    year: '2000',
    totalCards: 111,
    symbol: '◈',
    accentColor: '#0ea5e9',
    // Physical holos: 1-16; tcgdex labels all as 'Rare' but we split for pack variety
    rarityRanges: {
      'Rare Holo': [1,  16],
      'Rare':      [17, 25],
      'Uncommon':  [26, 54],
      'Common':    [55, 111],
    },
    rarityTotals: { 'Rare Holo': 16, 'Rare': 9, 'Uncommon': 29, 'Common': 57 },
  },
  {
    id: 'neo2',
    name: 'Neo Discovery',
    series: 'Neo',
    year: '2001',
    totalCards: 75,
    symbol: '✦',
    accentColor: '#8b5cf6',
    rarityRanges: {
      'Rare Holo': [1,  10],
      'Rare':      [11, 39],
      'Uncommon':  [40, 54],
      'Common':    [55, 75],
    },
    rarityTotals: { 'Rare Holo': 10, 'Rare': 29, 'Uncommon': 15, 'Common': 21 },
  },
  {
    id: 'neo3',
    name: 'Neo Revelation',
    series: 'Neo',
    year: '2001',
    totalCards: 64, // cards 65–66 (Shining Gyarados & Magikarp) are secret rares
    symbol: '✺',
    accentColor: '#be123c',
    rarityRanges: {
      'Rare Holo':   [1, 8],
      'Rare':        [9, 29],
      'Uncommon':    [[30, 40], [60, 63]],
      'Common':      [[41, 59], [64, 64]],
      'Secret Rare': [65, 66],
    },
    rarityTotals: { 'Rare Holo': 8, 'Rare': 21, 'Uncommon': 15, 'Common': 20, 'Secret Rare': 2 },
  },
  {
    id: 'neo4',
    name: 'Neo Destiny',
    series: 'Neo',
    year: '2002',
    totalCards: 105, // cards 106–113 (Shining Pokémon) are secret rares
    symbol: '⬡',
    accentColor: '#1d4ed8',
    rarityRanges: {
      'Rare Holo':   [1,   28],
      'Rare':        [29,  49],
      'Uncommon':    [50,  81],
      'Common':      [82,  105],
      'Secret Rare': [106, 113],
    },
    rarityTotals: { 'Rare Holo': 28, 'Rare': 21, 'Uncommon': 32, 'Common': 24, 'Secret Rare': 8 },
  },
  // ─── Legendary Collection ────────────────────────────────────────────────
  {
    id: 'lc',
    name: 'Legendary Collection',
    series: 'Legendary Collection',
    year: '2002',
    totalCards: 110,
    symbol: 'LC',
    accentColor: '#b45309',
    rarityRanges: {
      'Rare Holo': [1,  16],
      'Rare':      [17, 38],
      'Uncommon':  [39, 60],
      'Common':    [61, 110],
    },
    rarityTotals: { 'Rare Holo': 16, 'Rare': 22, 'Uncommon': 22, 'Common': 50 },
  },
  // ─── e-Card Series ───────────────────────────────────────────────────────
  {
    id: 'ecard1',
    name: 'Expedition Base Set',
    series: 'e-Card',
    year: '2002',
    totalCards: 165,
    symbol: 'EX',
    accentColor: '#047857',
    rarityRanges: {
      // Physical holos 1-17; tcgdex labels all as 'Rare'
      'Rare Holo': [1,  17],
      'Rare':      [18, 74],
      'Uncommon':  [[75, 94], [140, 164]],
      'Common':    [[95, 139], [165, 165]],
    },
    rarityTotals: { 'Rare Holo': 17, 'Rare': 57, 'Uncommon': 45, 'Common': 46 },
  },
  {
    id: 'ecard2',
    name: 'Aquapolis',
    series: 'e-Card',
    year: '2003',
    totalCards: 185,
    symbol: 'AQ',
    accentColor: '#1e40af',
    // H-prefix cards (H01–H32) are the holographic cards for this set
    rarityPrefixMap: { 'H': 'Rare Holo' },
    rarityRanges: {
      'Rare':     [[1, 46], [150, 150]],
      'Uncommon': [[47, 69], [120, 149]],
      'Common':   [70, 119],
    },
    rarityTotals: { 'Rare Holo': 32, 'Rare': 47, 'Uncommon': 57, 'Common': 49 },
  },
  {
    id: 'ecard3',
    name: 'Skyridge',
    series: 'e-Card',
    year: '2003',
    totalCards: 182,
    symbol: 'SK',
    accentColor: '#6d28d9',
    // H-prefix cards (H01–H32) are the holographic cards for this set
    rarityPrefixMap: { 'H': 'Rare Holo' },
    rarityRanges: {
      'Rare':     [[1, 39], [150, 150]],
      'Uncommon': [[40, 46], [120, 149]],
      'Common':   [47, 119],
    },
    rarityTotals: { 'Rare Holo': 32, 'Rare': 40, 'Uncommon': 37, 'Common': 73 },
  },
  // --- EX Series ---
  {
    id: 'ex1',
    name: 'EX Ruby & Sapphire',
    series: 'EX',
    year: '2003',
    totalCards: 109,
    symbol: 'ex',
    accentColor: '#dc2626',
    rarityRanges: {
      'Rare':     [1,  35],
      'Uncommon': [36, 69],
      'Common':   [70, 109],
    },
    rarityTotals: { 'Rare ex': 11, 'Rare': 24, 'Uncommon': 34, 'Common': 40 },
  },
  {
    id: 'ex2',
    name: 'EX Sandstorm',
    series: 'EX',
    year: '2003',
    totalCards: 100,
    symbol: 'ex',
    accentColor: '#d97706',
    rarityRanges: {
      'Rare':     [1,  25],
      'Uncommon': [26, 53],
      'Common':   [54, 100],
    },
    rarityTotals: { 'Rare ex': 8, 'Rare': 17, 'Uncommon': 28, 'Common': 47 },
  },
  {
    id: 'ex3',
    name: 'EX Dragon',
    series: 'EX',
    year: '2003',
    totalCards: 97,
    symbol: 'ex',
    accentColor: '#7c3aed',
    rarityRanges: {
      'Rare':        [1,  25],
      'Uncommon':    [26, 53],
      'Common':      [54, 97],
      'Secret Rare': [98, 100],
    },
    rarityTotals: { 'Rare ex': 9, 'Rare': 16, 'Uncommon': 28, 'Common': 44, 'Secret Rare': 3 },
  },
  {
    id: 'ex4',
    name: 'EX Team Magma vs Team Aqua',
    series: 'EX',
    year: '2004',
    totalCards: 95,
    symbol: 'ex',
    accentColor: '#3b82f6',
    rarityRanges: {
      'Rare':        [1,  21],
      'Uncommon':    [22, 47],
      'Common':      [48, 95],
      'Secret Rare': [96, 97],
    },
    rarityTotals: { 'Rare ex': 11, 'Rare': 10, 'Uncommon': 26, 'Common': 48, 'Secret Rare': 2 },
  },
  {
    id: 'ex5',
    name: 'EX Hidden Legends',
    series: 'EX',
    year: '2004',
    totalCards: 101,
    symbol: 'ex',
    accentColor: '#059669',
    rarityRanges: {
      'Rare':        [1,  26],
      'Uncommon':    [27, 55],
      'Common':      [56, 101],
      'Secret Rare': [102, 102],
    },
    rarityTotals: { 'Rare ex': 10, 'Rare': 16, 'Uncommon': 29, 'Common': 46, 'Secret Rare': 1 },
  },
  {
    id: 'ex6',
    name: 'EX FireRed & LeafGreen',
    series: 'EX',
    year: '2004',
    totalCards: 112,
    symbol: 'ex',
    accentColor: '#f97316',
    rarityRanges: {
      'Rare':        [1,  27],
      'Uncommon':    [28, 57],
      'Common':      [58, 112],
      'Secret Rare': [113, 116],
    },
    rarityTotals: { 'Rare ex': 12, 'Rare': 15, 'Uncommon': 30, 'Common': 55, 'Secret Rare': 4 },
  },
  {
    id: 'ex7',
    name: 'EX Team Rocket Returns',
    series: 'EX',
    year: '2004',
    totalCards: 109,
    symbol: 'ex',
    accentColor: '#9333ea',
    rarityRanges: {
      'Rare':        [1,  28],
      'Uncommon':    [29, 58],
      'Common':      [59, 109],
      'Secret Rare': [110, 111],
    },
    rarityTotals: { 'Rare ex': 15, 'Rare': 13, 'Uncommon': 30, 'Common': 51, 'Secret Rare': 2 },
  },
  {
    id: 'ex8',
    name: 'EX Deoxys',
    series: 'EX',
    year: '2005',
    totalCards: 107,
    symbol: 'ex',
    accentColor: '#06b6d4',
    rarityRanges: {
      'Rare':        [1,  24],
      'Uncommon':    [25, 54],
      'Common':      [55, 107],
      'Secret Rare': [108, 108],
    },
    rarityTotals: { 'Rare ex': 12, 'Rare': 12, 'Uncommon': 30, 'Common': 53, 'Secret Rare': 1 },
  },
  {
    id: 'ex9',
    name: 'EX Emerald',
    series: 'EX',
    year: '2005',
    totalCards: 106,
    symbol: 'ex',
    accentColor: '#22c55e',
    rarityRanges: {
      'Rare':        [1,  22],
      'Uncommon':    [23, 51],
      'Common':      [52, 106],
      'Secret Rare': [107, 107],
    },
    rarityTotals: { 'Rare ex': 10, 'Rare': 12, 'Uncommon': 29, 'Common': 55, 'Secret Rare': 1 },
  },
  {
    id: 'ex10',
    name: 'EX Unseen Forces',
    series: 'EX',
    year: '2005',
    totalCards: 115,
    symbol: 'ex',
    accentColor: '#f59e0b',
    rarityRanges: {
      'Rare':        [1,  30],
      'Uncommon':    [31, 65],
      'Common':      [66, 115],
      'Secret Rare': [116, 117],
    },
    rarityTotals: { 'Rare ex': 17, 'Rare': 13, 'Uncommon': 35, 'Common': 50, 'Secret Rare': 2 },
    // mergeSets: ['exu'], // re-enable when TCGdex adds Unown card images
  },
  {
    id: 'ex11',
    name: 'EX Delta Species',
    series: 'EX',
    year: '2005',
    totalCards: 113,
    symbol: 'ex',
    accentColor: '#8b5cf6',
    rarityRanges: {
      'Rare':        [1,  26],
      'Uncommon':    [27, 57],
      'Common':      [58, 113],
      'Secret Rare': [114, 114],
    },
    rarityTotals: { 'Rare ex': 11, 'Rare': 15, 'Uncommon': 31, 'Common': 56, 'Secret Rare': 1 },
  },
  {
    id: 'ex12',
    name: 'EX Legend Maker',
    series: 'EX',
    year: '2006',
    totalCards: 92,
    symbol: 'ex',
    accentColor: '#0284c7',
    rarityRanges: {
      'Rare':        [1,  15],
      'Uncommon':    [16, 37],
      'Common':      [38, 92],
      'Secret Rare': [93, 93],
    },
    rarityTotals: { 'Rare ex': 7, 'Rare': 18, 'Uncommon': 22, 'Common': 45, 'Secret Rare': 1 },
  },
  {
    id: 'ex13',
    name: 'EX Holon Phantoms',
    series: 'EX',
    year: '2006',
    totalCards: 110,
    symbol: 'ex',
    accentColor: '#7c3aed',
    rarityRanges: {
      'Rare':        [1,   17],
      'Uncommon':    [18,  51],
      'Common':      [52,  110],
      'Secret Rare': [111, 111],
    },
    rarityTotals: { 'Rare ex': 3, 'Rare': 20, 'Uncommon': 34, 'Common': 53, 'Secret Rare': 1 },
  },
  {
    id: 'ex14',
    name: 'EX Crystal Guardians',
    series: 'EX',
    year: '2006',
    totalCards: 100,
    symbol: 'ex',
    accentColor: '#06b6d4',
    rarityRanges: {
      'Rare':     [1,  13],
      'Uncommon': [14, 41],
      'Common':   [42, 100],
    },
    rarityTotals: { 'Rare ex': 10, 'Rare': 15, 'Uncommon': 28, 'Common': 47 },
  },
  {
    id: 'ex15',
    name: 'EX Dragon Frontiers',
    series: 'EX',
    year: '2006',
    totalCards: 101,
    symbol: 'ex',
    accentColor: '#dc2626',
    rarityRanges: {
      'Rare':     [1,  12],
      'Uncommon': [13, 37],
      'Common':   [38, 101],
    },
    rarityTotals: { 'Rare ex': 10, 'Rare': 14, 'Uncommon': 25, 'Common': 52 },
  },
  {
    id: 'ex16',
    name: 'EX Power Keepers',
    series: 'EX',
    year: '2007',
    totalCards: 108,
    symbol: 'ex',
    accentColor: '#f59e0b',
    rarityRanges: {
      'Rare':     [1,  13],
      'Uncommon': [14, 35],
      'Common':   [36, 108],
    },
    rarityTotals: { 'Rare ex': 8, 'Rare': 16, 'Uncommon': 22, 'Common': 62 },
  },
  // --- Diamond & Pearl Series ---
  {
    id: 'dp1',
    name: 'Diamond & Pearl',
    series: 'Diamond & Pearl',
    year: '2007',
    totalCards: 130,
    symbol: '◇',
    accentColor: '#6366f1',
    rarityRanges: {
      'Rare Holo': [1,  29],
      'Rare':      [30, 63],
      'Uncommon':  [64, 68],
      'Rare LV.X': [120, 122],
      'Common':    [69, 119], // trainers; energies 123-130 fall through to inferRarity's 'Common' default
    },
    rarityTotals: { 'Rare LV.X': 3, 'Rare Holo': 29, 'Rare': 34, 'Uncommon': 5, 'Common': 59 },
  },
  {
    id: 'dp2',
    name: 'Mysterious Treasures',
    series: 'Diamond & Pearl',
    year: '2007',
    totalCards: 123,
    symbol: '◇',
    accentColor: '#0891b2',
    rarityRanges: {
      'Rare Holo': [1,  17],
      'Rare':      [18, 40],
      'Uncommon':  [41, 68],
      'Rare LV.X': [121, 123],
      'Common':    [69, 120],
    },
    rarityTotals: { 'Rare LV.X': 3, 'Rare Holo': 17, 'Rare': 23, 'Uncommon': 28, 'Common': 52 },
  },
  {
    id: 'dp3',
    name: 'Secret Wonders',
    series: 'Diamond & Pearl',
    year: '2007',
    totalCards: 132,
    symbol: '◇',
    accentColor: '#7c3aed',
    rarityRanges: {
      'Rare Holo': [1,  20],
      'Rare':      [21, 44],
      'Uncommon':  [45, 75],
      'Rare LV.X': [131, 132],
      'Common':    [76, 130],
    },
    rarityTotals: { 'Rare LV.X': 2, 'Rare Holo': 20, 'Rare': 24, 'Uncommon': 31, 'Common': 55 },
  },
  {
    id: 'dp4',
    name: 'Great Encounters',
    series: 'Diamond & Pearl',
    year: '2008',
    totalCards: 106,
    symbol: '◇',
    accentColor: '#16a34a',
    rarityRanges: {
      'Rare Holo': [1,  19],
      'Rare':      [20, 32],
      'Uncommon':  [33, 59],
      'Rare LV.X': [103, 106],
      'Common':    [60, 102],
    },
    rarityTotals: { 'Rare LV.X': 4, 'Rare Holo': 19, 'Rare': 13, 'Uncommon': 27, 'Common': 43 },
  },
  {
    id: 'dp5',
    name: 'Majestic Dawn',
    series: 'Diamond & Pearl',
    year: '2008',
    totalCards: 100,
    symbol: '◇',
    accentColor: '#f97316',
    rarityRanges: {
      'Rare Holo': [1,  16],
      'Rare':      [17, 34],
      'Uncommon':  [35, 49],
      'Rare LV.X': [97, 100],
      'Common':    [50, 96],
    },
    rarityTotals: { 'Rare LV.X': 4, 'Rare Holo': 16, 'Rare': 18, 'Uncommon': 15, 'Common': 47 },
  },
  {
    id: 'dp6',
    name: 'Legends Awakened',
    series: 'Diamond & Pearl',
    year: '2008',
    totalCards: 146,
    symbol: '◇',
    accentColor: '#dc2626',
    rarityRanges: {
      'Rare Holo': [1,  17],
      'Rare':      [18, 45],
      'Uncommon':  [46, 82],
      'Rare LV.X': [140, 146],
      'Common':    [83, 139],
    },
    rarityTotals: { 'Rare LV.X': 7, 'Rare Holo': 17, 'Rare': 28, 'Uncommon': 37, 'Common': 57 },
  },
  {
    id: 'dp7',
    name: 'Stormfront',
    series: 'Diamond & Pearl',
    year: '2008',
    totalCards: 100,
    symbol: '◇',
    accentColor: '#334155',
    rarityPrefixMap: { 'SH': 'Rare Shiny' }, // SH1-SH3 shiny sub-set
    rarityRanges: {
      'Rare Holo': [1,  16],
      'Rare':      [17, 25],
      'Uncommon':  [26, 45],
      'Rare LV.X': [96, 100],
      'Common':    [46, 95],
    },
    rarityTotals: { 'Rare Shiny': 3, 'Rare LV.X': 5, 'Rare Holo': 16, 'Rare': 9, 'Uncommon': 20, 'Common': 50 },
  },
  {
    id: 'pl1',
    name: 'Platinum',
    series: 'Platinum',
    year: '2009',
    totalCards: 133,
    symbol: 'Pt',
    accentColor: '#4f46e5',
    rarityRanges: {
      'Rare Holo': [1, 17],
      'Rare':      [18, 38],
      'Uncommon':  [39, 69],
      'Rare LV.X': [127, 133],
      'Common':    [70, 126],
    },
    rarityTotals: { 'Rare LV.X': 7, 'Rare Holo': 17, 'Rare': 21, 'Uncommon': 31, 'Common': 57 },
  },
  {
    id: 'pl2',
    name: 'Rising Rivals',
    series: 'Platinum',
    year: '2009',
    totalCards: 111,
    symbol: 'Pt',
    accentColor: '#0f766e',
    rarityRanges: {
      'Rare Holo': [1, 16],
      'Rare':      [17, 32],
      'Uncommon':  [33, 58],
      'Common':    [59, 103],
      'Rare LV.X': [104, 111],
    },
    rarityTotals: { 'Rare LV.X': 8, 'Rare Holo': 16, 'Rare': 16, 'Uncommon': 26, 'Common': 45 },
  },
  {
    id: 'pl3',
    name: 'Supreme Victors',
    series: 'Platinum',
    year: '2009',
    totalCards: 147,
    symbol: 'Pt',
    accentColor: '#9f1239',
    rarityRanges: {
      'Rare Holo': [1, 22],
      'Rare':      [23, 48],
      'Uncommon':  [49, 86],
      'Common':    [87, 142],
      'Rare LV.X': [143, 147],
    },
    rarityTotals: { 'Rare LV.X': 5, 'Rare Holo': 22, 'Rare': 26, 'Uncommon': 38, 'Common': 56 },
  },
  {
    id: 'pl4',
    name: 'Arceus',
    series: 'Platinum',
    year: '2009',
    totalCards: 99,
    symbol: 'Pt',
    accentColor: '#7c3aed',
    rarityRanges: {
      'Rare Holo': [1, 15],
      'Rare':      [16, 31],
      'Uncommon':  [32, 57],
      'Common':    [58, 93],
      'Rare LV.X': [94, 99],
    },
    rarityTotals: { 'Rare LV.X': 6, 'Rare Holo': 15, 'Rare': 16, 'Uncommon': 26, 'Common': 36 },
  },
  // --- HeartGold & SoulSilver Series ---
  {
    id: 'hgss1',
    name: 'HeartGold & SoulSilver',
    series: 'HeartGold & SoulSilver',
    year: '2010',
    totalCards: 123,
    symbol: 'HG',
    accentColor: '#b45309',
    // Alph Lithograph ONE is this set's secret rare.
    rarityPrefixMap: { 'ONE': 'Secret Rare' },
    rarityRanges: {
      'Rare Holo': [1, 14],
      'Rare':      [15, 34],
      'Uncommon':  [35, 64],
      'Common':    [65, 123],
    },
    rarityTotals: { 'Secret Rare': 1, 'Rare Holo': 14, 'Rare': 20, 'Uncommon': 30, 'Common': 59 },
  },
  {
    id: 'hgss2',
    name: 'Unleashed',
    series: 'HeartGold & SoulSilver',
    year: '2010',
    totalCards: 95,
    symbol: 'HG',
    accentColor: '#0f766e',
    // Alph Lithograph TWO is this set's secret rare.
    rarityPrefixMap: { 'TWO': 'Secret Rare' },
    rarityRanges: {
      'Rare Holo': [1, 12],
      'Rare':      [13, 26],
      'Uncommon':  [27, 52],
      'Common':    [53, 95],
    },
    rarityTotals: { 'Secret Rare': 1, 'Rare Holo': 12, 'Rare': 14, 'Uncommon': 26, 'Common': 43 },
  },
  {
    id: 'hgss3',
    name: 'Undaunted',
    series: 'HeartGold & SoulSilver',
    year: '2010',
    totalCards: 90,
    symbol: 'HG',
    accentColor: '#475569',
    // Alph Lithograph THREE is this set's secret rare.
    rarityPrefixMap: { 'THREE': 'Secret Rare' },
    rarityRanges: {
      'Rare Holo': [1, 11],
      'Rare':      [12, 24],
      'Uncommon':  [25, 49],
      'Common':    [50, 90],
    },
    rarityTotals: { 'Secret Rare': 1, 'Rare Holo': 11, 'Rare': 13, 'Uncommon': 25, 'Common': 41 },
  },
  {
    id: 'hgss4',
    name: 'Triumphant',
    series: 'HeartGold & SoulSilver',
    year: '2010',
    totalCards: 102,
    symbol: 'HG',
    accentColor: '#7c3aed',
    // Alph Lithograph FOUR is this set's secret rare.
    rarityPrefixMap: { 'FOUR': 'Secret Rare' },
    rarityRanges: {
      'Rare Holo': [1, 13],
      'Rare':      [14, 28],
      'Uncommon':  [29, 55],
      'Common':    [56, 102],
    },
    rarityTotals: { 'Secret Rare': 1, 'Rare Holo': 13, 'Rare': 15, 'Uncommon': 27, 'Common': 47 },
  },
  {
    id: 'col1',
    name: 'Call of Legends',
    series: 'HeartGold & SoulSilver',
    year: '2011',
    totalCards: 95,
    symbol: 'CL',
    accentColor: '#0ea5e9',
    // Shiny Legendary cards SL1-SL11 are this set's secret rares.
    rarityPrefixMap: { 'SL': 'Secret Rare' },
    rarityRanges: {
      'Rare Holo': [1, 11],
      'Rare':      [12, 22],
      'Uncommon':  [23, 48],
      'Common':    [49, 95],
    },
    rarityTotals: { 'Secret Rare': 11, 'Rare Holo': 11, 'Rare': 11, 'Uncommon': 26, 'Common': 47 },
  },
  {
    id: 'bw1',
    name: 'Black & White',
    series: 'Black & White',
    year: '2011',
    totalCards: 114,
    symbol: 'BW',
    accentColor: '#0f172a',
    rarityRanges: {
      'Common':      [1, 44],
      'Uncommon':    [45, 81],
      'Rare':        [82, 112],
      'Ultra Rare':  [113, 114],
      'Secret Rare': [115, 115],
    },
    rarityTotals: { 'Common': 44, 'Uncommon': 37, 'Rare': 31, 'Ultra Rare': 2, 'Secret Rare': 1 },
  },
  {
    id: 'bw2',
    name: 'Emerging Powers',
    series: 'Black & White',
    year: '2011',
    totalCards: 98,
    symbol: 'BW',
    accentColor: '#0ea5e9',
    rarityRanges: {
      'Common':      [1, 34],
      'Uncommon':    [35, 65],
      'Rare':        [66, 96],
      'Ultra Rare':  [97, 98],
    },
    rarityTotals: { 'Common': 34, 'Uncommon': 31, 'Rare': 31, 'Ultra Rare': 2 },
  },
  {
    id: 'bw3',
    name: 'Noble Victories',
    series: 'Black & White',
    year: '2011',
    totalCards: 101,
    symbol: 'BW',
    accentColor: '#6366f1',
    rarityRanges: {
      'Common':      [1, 31],
      'Uncommon':    [32, 61],
      'Rare':        [62, 96],
      'Ultra Rare':  [97, 101],
      'Secret Rare': [102, 102],
    },
    rarityTotals: { 'Common': 31, 'Uncommon': 30, 'Rare': 35, 'Ultra Rare': 5, 'Secret Rare': 1 },
  },
  {
    id: 'bw4',
    name: 'Next Destinies',
    series: 'Black & White',
    year: '2012',
    totalCards: 99,
    symbol: 'BW',
    accentColor: '#8b5cf6',
    rarityRanges: {
      'Common':      [1, 29],
      'Uncommon':    [30, 56],
      'Rare':        [57, 93],
      'Ultra Rare':  [94, 99],
      'Secret Rare': [100, 103],
    },
    rarityTotals: { 'Common': 29, 'Uncommon': 27, 'Rare': 37, 'Ultra Rare': 6, 'Secret Rare': 4 },
  },
  {
    id: 'bw5',
    name: 'Dark Explorers',
    series: 'Black & White',
    year: '2012',
    totalCards: 108,
    symbol: 'BW',
    accentColor: '#334155',
    rarityRanges: {
      'Common':      [1, 33],
      'Uncommon':    [34, 68],
      'Rare':        [69, 102],
      'Ultra Rare':  [103, 108],
      'Secret Rare': [109, 111],
    },
    rarityTotals: { 'Common': 33, 'Uncommon': 35, 'Rare': 34, 'Ultra Rare': 6, 'Secret Rare': 3 },
  },
  {
    id: 'bw6',
    name: 'Dragons Exalted',
    series: 'Black & White',
    year: '2012',
    totalCards: 124,
    symbol: 'BW',
    accentColor: '#f59e0b',
    rarityRanges: {
      'Common':      [1, 39],
      'Uncommon':    [40, 75],
      'Rare':        [76, 118],
      'Ultra Rare':  [119, 124],
      'Secret Rare': [125, 128],
    },
    rarityTotals: { 'Common': 39, 'Uncommon': 36, 'Rare': 43, 'Ultra Rare': 6, 'Secret Rare': 4 },
  },
  {
    id: 'bw7',
    name: 'Boundaries Crossed',
    series: 'Black & White',
    year: '2012',
    totalCards: 149,
    symbol: 'BW',
    accentColor: '#22c55e',
    rarityRanges: {
      'Common':      [1, 50],
      'Uncommon':    [51, 93],
      'Rare':        [94, 140],
      'Ultra Rare':  [141, 149],
      'Secret Rare': [150, 153],
    },
    rarityTotals: { 'Common': 50, 'Uncommon': 43, 'Rare': 47, 'Ultra Rare': 9, 'Secret Rare': 4 },
  },
  {
    id: 'bw8',
    name: 'Plasma Storm',
    series: 'Black & White',
    year: '2013',
    totalCards: 135,
    symbol: 'BW',
    accentColor: '#06b6d4',
    rarityRanges: {
      'Common':      [1, 41],
      'Uncommon':    [42, 83],
      'Rare':        [84, 130],
      'Ultra Rare':  [131, 135],
      'Secret Rare': [136, 138],
    },
    rarityTotals: { 'Common': 41, 'Uncommon': 42, 'Rare': 47, 'Ultra Rare': 5, 'Secret Rare': 3 },
  },
  {
    id: 'bw9',
    name: 'Plasma Freeze',
    series: 'Black & White',
    year: '2013',
    totalCards: 116,
    symbol: 'BW',
    accentColor: '#3b82f6',
    rarityRanges: {
      'Common':      [1, 32],
      'Uncommon':    [33, 64],
      'Rare':        [65, 108],
      'Ultra Rare':  [109, 116],
      'Secret Rare': [117, 122],
    },
    rarityTotals: { 'Common': 32, 'Uncommon': 32, 'Rare': 44, 'Ultra Rare': 8, 'Secret Rare': 6 },
  },
  {
    id: 'bw10',
    name: 'Plasma Blast',
    series: 'Black & White',
    year: '2013',
    totalCards: 101,
    symbol: 'BW',
    accentColor: '#6366f1',
    rarityRanges: {
      'Common':      [1, 26],
      'Uncommon':    [27, 59],
      'Rare':        [60, 95],
      'Ultra Rare':  [96, 101],
      'Secret Rare': [102, 105],
    },
    rarityTotals: { 'Common': 26, 'Uncommon': 33, 'Rare': 36, 'Ultra Rare': 6, 'Secret Rare': 4 },
  },
  {
    id: 'bw11',
    name: 'Legendary Treasures',
    series: 'Black & White',
    year: '2013',
    totalCards: 113,
    symbol: 'BW',
    accentColor: '#f97316',
    rarityRanges: {
      'Common':      [1, 27],
      'Uncommon':    [28, 59],
      'Rare':        [60, 113],
      'Secret Rare': [114, 115],
    },
    // Includes the RC subset totals from this release.
    rarityTotals: { 'Common': 37, 'Uncommon': 41, 'Rare': 55, 'Ultra Rare': 5, 'Secret Rare': 2 },
  },
  {
    id: 'xy1',
    name: 'XY',
    series: 'XY',
    year: '2014',
    totalCards: 146,
    symbol: 'XY',
    accentColor: '#10b981',
    rarityRanges: {
      'Common':   [1, 48],
      'Uncommon': [49, 90],
      'Rare':     [91, 132],
      'Rare ex':  [133, 146],
    },
    rarityTotals: { 'Common': 48, 'Uncommon': 42, 'Rare': 42, 'Rare ex': 14, 'Mega EX': 2 },
  },
  {
    id: 'xy2',
    name: 'Flashfire',
    series: 'XY',
    year: '2014',
    totalCards: 106,
    secretStart: 108,
    symbol: 'XY',
    accentColor: '#ef4444',
    rarityRanges: {
      'Common':      [1, 31],
      'Uncommon':    [32, 64],
      'Rare':        [65, 92],
      'Rare ex':     [93, 107],
      'Secret Rare': [108, 110],
    },
    rarityTotals: { 'Common': 31, 'Uncommon': 33, 'Rare': 28, 'Rare ex': 15, 'Mega EX': 6, 'Secret Rare': 3 },
  },
  {
    id: 'xy3',
    name: 'Furious Fists',
    series: 'XY',
    year: '2014',
    totalCards: 111,
    secretStart: 113,
    symbol: 'XY',
    accentColor: '#f97316',
    rarityRanges: {
      'Common':      [1, 29],
      'Uncommon':    [30, 68],
      'Rare':        [69, 98],
      'Rare ex':     [99, 112],
      'Secret Rare': [113, 114],
    },
    rarityTotals: { 'Common': 29, 'Uncommon': 39, 'Rare': 30, 'Rare ex': 14, 'Mega EX': 5, 'Secret Rare': 2 },
  },
  {
    id: 'xy4',
    name: 'Phantom Forces',
    series: 'XY',
    year: '2014',
    totalCards: 119,
    secretStart: 122,
    symbol: 'XY',
    accentColor: '#8b5cf6',
    rarityRanges: {
      'Common':      [1, 34],
      'Uncommon':    [35, 71],
      'Rare':        [72, 106],
      'Rare ex':     [107, 121],
      'Secret Rare': [122, 124],
    },
    rarityTotals: { 'Common': 34, 'Uncommon': 37, 'Rare': 35, 'Rare ex': 15, 'Mega EX': 5, 'Secret Rare': 3 },
  },
  {
    id: 'xy5',
    name: 'Primal Clash',
    series: 'XY',
    year: '2015',
    totalCards: 160,
    secretStart: 161,
    symbol: 'XY',
    accentColor: '#0ea5e9',
    rarityRanges: {
      'Common':      [1, 39],
      'Uncommon':    [40, 89],
      'Rare':        [90, 132],
      'Rare ex':     [133, 160],
      'Secret Rare': [161, 164],
    },
    rarityTotals: { 'Common': 39, 'Uncommon': 50, 'Rare': 43, 'Rare ex': 28, 'Mega EX': 4, 'Secret Rare': 4 },
  },
  {
    id: 'xy6',
    name: 'Roaring Skies',
    series: 'XY',
    year: '2015',
    totalCards: 108,
    secretStart: 109,
    symbol: 'XY',
    accentColor: '#14b8a6',
    rarityRanges: {
      'Common':      [1, 26],
      'Uncommon':    [27, 59],
      'Rare':        [60, 86],
      'Rare ex':     [87, 108],
      'Secret Rare': [109, 110],
    },
    rarityTotals: { 'Common': 26, 'Uncommon': 33, 'Rare': 29, 'Rare ex': 18, 'Mega EX': 6, 'Ultra Rare': 4, 'Secret Rare': 2 },
  },
  {
    id: 'xy7',
    name: 'Ancient Origins',
    series: 'XY',
    year: '2015',
    totalCards: 98,
    secretStart: 99,
    symbol: 'XY',
    accentColor: '#f59e0b',
    rarityRanges: {
      'Common':      [1, 23],
      'Uncommon':    [24, 52],
      'Rare':        [53, 75],
      'Rare ex':     [76, 98],
      'Secret Rare': [99, 103],
    },
    rarityTotals: { 'Common': 23, 'Uncommon': 29, 'Rare': 21, 'Rare ex': 18, 'Mega EX': 6, 'Ultra Rare': 5, 'Secret Rare': 5 },
  },
  {
    id: 'xy8',
    name: 'BREAKthrough',
    series: 'XY',
    year: '2015',
    totalCards: 162,
    secretStart: 163,
    symbol: 'XY',
    accentColor: '#f97316',
    rarityRanges: {
      'Common':      [1, 53],
      'Uncommon':    [54, 101],
      'Rare':        [102, 146],
      'Rare ex':     [147, 162],
      'Secret Rare': [163, 165],
    },
    rarityTotals: { 'Common': 53, 'Uncommon': 48, 'Rare': 31, 'Rare BREAK': 6, 'Rare ex': 16, 'Mega EX': 6, 'Ultra Rare': 8, 'Secret Rare': 3 },
  },
  {
    id: 'xy9',
    name: 'BREAKpoint',
    series: 'XY',
    year: '2016',
    totalCards: 122,
    secretStart: 123,
    symbol: 'XY',
    accentColor: '#ef4444',
    rarityRanges: {
      'Common':      [1, 33],
      'Uncommon':    [34, 77],
      'Rare':        [78, 107],
      'Rare ex':     [108, 122],
      'Secret Rare': [123, 123],
    },
    rarityTotals: { 'Common': 33, 'Uncommon': 44, 'Rare': 18, 'Rare BREAK': 5, 'Rare ex': 15, 'Mega EX': 5, 'Ultra Rare': 10, 'Secret Rare': 1 },
  },
  {
    id: 'xy10',
    name: 'Fates Collide',
    series: 'XY',
    year: '2016',
    totalCards: 124,
    secretStart: 125,
    symbol: 'XY',
    accentColor: '#a855f7',
    rarityRanges: {
      'Common':      [1, 26],
      'Uncommon':    [27, 73],
      'Rare':        [74, 100],
      'Rare ex':     [101, 124],
      'Secret Rare': [125, 129],
    },
    rarityTotals: { 'Common': 26, 'Uncommon': 47, 'Rare': 27, 'Rare ex': 24, 'Mega EX': 5, 'Ultra Rare': 4, 'Secret Rare': 5 },
  },
  {
    id: 'xy11',
    name: 'Steam Siege',
    series: 'XY',
    year: '2016',
    totalCards: 114,
    secretStart: 115,
    symbol: 'XY',
    accentColor: '#64748b',
    rarityRanges: {
      'Common':      [1, 31],
      'Uncommon':    [32, 61],
      'Rare':        [62, 93],
      'Rare ex':     [94, 114],
      'Secret Rare': [115, 116],
    },
    rarityTotals: { 'Common': 31, 'Uncommon': 30, 'Rare': 32, 'Rare ex': 14, 'Mega EX': 4, 'Ultra Rare': 7, 'Secret Rare': 2 },
  },
  {
    id: 'xy12',
    name: 'Evolutions',
    series: 'XY',
    year: '2016',
    totalCards: 108,
    secretStart: 109,
    symbol: 'XY',
    accentColor: '#22c55e',
    rarityRanges: {
      'Common':      [1, 33],
      'Uncommon':    [34, 61],
      'Rare':        [62, 83],
      'Rare ex':     [84, 108],
      'Secret Rare': [109, 113],
    },
    rarityTotals: { 'Common': 33, 'Uncommon': 28, 'Rare': 22, 'Rare ex': 19, 'Mega EX': 9, 'Ultra Rare': 6, 'Secret Rare': 5 },
  },
  {
    id: 'sm1',
    name: 'Sun & Moon',
    series: 'Sun & Moon',
    year: '2017',
    totalCards: 149,
    secretStart: 150,
    symbol: 'SM',
    accentColor: '#f59e0b',
    rarityRanges: {
      'Common':      [1, 53],
      'Uncommon':    [54, 102],
      'Rare':        [103, 135],
      'Rare ex':     [136, 149],
      'Secret Rare': [150, 172],
    },
    rarityTotals: { 'Common': 53, 'Uncommon': 49, 'Rare': 33, 'Rare ex': 27, 'Rare GX': 27, 'Ultra Rare': 23, 'Secret Rare': 14 },
  },
  {
    id: 'sm2',
    name: 'Guardians Rising',
    series: 'Sun & Moon',
    year: '2017',
    totalCards: 145,
    secretStart: 146,
    symbol: 'SM',
    accentColor: '#0ea5e9',
    rarityRanges: {
      'Common':      [1, 40],
      'Uncommon':    [41, 76],
      'Rare':        [77, 145],
      'Secret Rare': [146, 169],
    },
    rarityTotals: { 'Common': 40, 'Uncommon': 36, 'Rare': 43, 'Rare ex': 39, 'Rare GX': 39, 'Ultra Rare': 26, 'Secret Rare': 24 },
  },
  {
    id: 'sm3',
    name: 'Burning Shadows',
    series: 'Sun & Moon',
    year: '2017',
    totalCards: 147,
    secretStart: 148,
    symbol: 'SM',
    accentColor: '#f97316',
    rarityRanges: {
      'Common':      [1, 39],
      'Uncommon':    [40, 77],
      'Rare':        [78, 147],
      'Secret Rare': [148, 169],
    },
    rarityTotals: { 'Common': 39, 'Uncommon': 38, 'Rare': 40, 'Rare ex': 38, 'Rare GX': 38, 'Ultra Rare': 30, 'Secret Rare': 22 },
  },
  {
    id: 'sm4',
    name: 'Crimson Invasion',
    series: 'Sun & Moon',
    year: '2017',
    totalCards: 111,
    secretStart: 112,
    symbol: 'SM',
    accentColor: '#dc2626',
    rarityRanges: {
      'Common':      [1, 34],
      'Uncommon':    [35, 60],
      'Rare':        [61, 111],
      'Secret Rare': [112, 125],
    },
    rarityTotals: { 'Common': 34, 'Uncommon': 26, 'Rare': 33, 'Rare ex': 25, 'Rare GX': 25, 'Ultra Rare': 19, 'Secret Rare': 13 },
  },
  {
    id: 'sm5',
    name: 'Ultra Prism',
    series: 'Sun & Moon',
    year: '2018',
    totalCards: 156,
    secretStart: 157,
    symbol: 'SM',
    accentColor: '#6366f1',
    rarityRanges: {
      'Common':      [1, 45],
      'Uncommon':    [46, 89],
      'Rare':        [90, 156],
      'Secret Rare': [157, 173],
    },
    rarityTotals: { 'Common': 45, 'Uncommon': 44, 'Rare': 42, 'Rare ex': 27, 'Rare GX': 27, 'Ultra Rare': 25, 'Secret Rare': 17 },
  },
  {
    id: 'sm6',
    name: 'Forbidden Light',
    series: 'Sun & Moon',
    year: '2018',
    totalCards: 131,
    secretStart: 132,
    symbol: 'SM',
    accentColor: '#8b5cf6',
    rarityRanges: {
      'Common':      [1, 33],
      'Uncommon':    [34, 69],
      'Rare':        [70, 131],
      'Secret Rare': [132, 146],
    },
    rarityTotals: { 'Common': 33, 'Uncommon': 36, 'Rare': 41, 'Rare ex': 26, 'Rare GX': 26, 'Ultra Rare': 21, 'Secret Rare': 15 },
  },
  {
    id: 'sm7',
    name: 'Celestial Storm',
    series: 'Sun & Moon',
    year: '2018',
    totalCards: 168,
    secretStart: 169,
    symbol: 'SM',
    accentColor: '#0ea5e9',
    rarityRanges: {
      'Common':      [1, 40],
      'Uncommon':    [41, 102],
      'Rare':        [103, 168],
      'Secret Rare': [169, 183],
    },
    rarityTotals: { 'Common': 40, 'Uncommon': 62, 'Rare': 38, 'Rare ex': 29, 'Rare GX': 29, 'Ultra Rare': 28, 'Secret Rare': 15 },
  },
  {
    id: 'sm8',
    name: 'Lost Thunder',
    series: 'Sun & Moon',
    year: '2018',
    totalCards: 214,
    secretStart: 215,
    symbol: 'SM',
    accentColor: '#f59e0b',
    rarityRanges: {
      'Common':      [1, 56],
      'Uncommon':    [57, 115],
      'Rare':        [116, 214],
      'Secret Rare': [215, 236],
    },
    rarityTotals: { 'Common': 56, 'Uncommon': 59, 'Rare': 66, 'Rare ex': 39, 'Rare GX': 39, 'Ultra Rare': 33, 'Secret Rare': 22 },
  },
  {
    id: 'sm9',
    name: 'Team Up',
    series: 'Sun & Moon',
    year: '2019',
    totalCards: 181,
    secretStart: 182,
    symbol: 'SM',
    accentColor: '#3b82f6',
    rarityRanges: {
      'Common':      [1, 45],
      'Uncommon':    [46, 93],
      'Rare':        [94, 181],
      'Secret Rare': [182, 196],
    },
    rarityTotals: { 'Common': 45, 'Uncommon': 48, 'Rare': 54, 'Rare ex': 34, 'Rare GX': 34, 'Ultra Rare': 34, 'Secret Rare': 15 },
  },
  {
    id: 'sm10',
    name: 'Unbroken Bonds',
    series: 'Sun & Moon',
    year: '2019',
    totalCards: 214,
    secretStart: 215,
    symbol: 'SM',
    accentColor: '#ef4444',
    rarityRanges: {
      'Common':      [1, 62],
      'Uncommon':    [63, 115],
      'Rare':        [116, 214],
      'Secret Rare': [215, 234],
    },
    rarityTotals: { 'Common': 62, 'Uncommon': 53, 'Rare': 61, 'Rare ex': 46, 'Rare GX': 46, 'Ultra Rare': 38, 'Secret Rare': 20 },
  },
  {
    id: 'sm11',
    name: 'Unified Minds',
    series: 'Sun & Moon',
    year: '2019',
    totalCards: 236,
    secretStart: 237,
    symbol: 'SM',
    accentColor: '#8b5cf6',
    rarityRanges: {
      'Common':      [1, 65],
      'Uncommon':    [66, 137],
      'Rare':        [138, 236],
      'Secret Rare': [237, 258],
    },
    rarityTotals: { 'Common': 65, 'Uncommon': 72, 'Rare': 59, 'Rare ex': 47, 'Rare GX': 47, 'Ultra Rare': 40, 'Secret Rare': 22 },
  },
  {
    id: 'sm12',
    name: 'Cosmic Eclipse',
    series: 'Sun & Moon',
    year: '2019',
    totalCards: 236,
    secretStart: 237,
    symbol: 'SM',
    accentColor: '#6366f1',
    rarityRanges: {
      'Common':      [1, 67],
      'Uncommon':    [68, 133],
      'Rare':        [134, 236],
      'Secret Rare': [237, 271],
    },
    rarityTotals: { 'Common': 67, 'Uncommon': 66, 'Rare': 60, 'Rare ex': 48, 'Rare GX': 48, 'Ultra Rare': 43, 'Secret Rare': 35 },
  },
  {
    id: 'swsh1',
    name: 'Sword & Shield',
    series: 'Sword & Shield',
    year: '2020',
    totalCards: 202,
    secretStart: 203,
    symbol: 'SWSH',
    accentColor: '#06b6d4',
    rarityRanges: {
      'Common':      [1, 60],
      'Uncommon':    [61, 116],
      'Rare':        [117, 202],
      'Secret Rare': [203, 216],
    },
    rarityTotals: { 'Common': 60, 'Uncommon': 56, 'Rare': 47, 'Rare ex': 31, 'Rare V': 31, 'Rare VMAX': 8, 'Ultra Rare': 16, 'Secret Rare': 14 },
  },
  {
    id: 'swsh2',
    name: 'Rebel Clash',
    series: 'Sword & Shield',
    year: '2020',
    totalCards: 192,
    secretStart: 193,
    symbol: 'SWSH',
    accentColor: '#ef4444',
    rarityRanges: {
      'Common':      [1, 50],
      'Uncommon':    [51, 101],
      'Rare':        [102, 192],
      'Secret Rare': [193, 209],
    },
    rarityTotals: { 'Common': 50, 'Uncommon': 51, 'Rare': 32, 'Rare ex': 44, 'Rare V': 30, 'Rare VMAX': 14, 'Ultra Rare': 18, 'Secret Rare': 17 },
  },
  {
    id: 'swsh3',
    name: 'Darkness Ablaze',
    series: 'Sword & Shield',
    year: '2020',
    totalCards: 189,
    secretStart: 190,
    symbol: 'SWSH',
    accentColor: '#f59e0b',
    rarityRanges: {
      'Common':      [1, 53],
      'Uncommon':    [54, 103],
      'Rare':        [104, 189],
      'Secret Rare': [190, 201],
    },
    rarityTotals: { 'Common': 53, 'Uncommon': 50, 'Rare': 34, 'Rare ex': 35, 'Rare V': 23, 'Rare VMAX': 12, 'Ultra Rare': 13, 'Secret Rare': 12 },
  },
  {
    id: 'swsh4',
    name: 'Vivid Voltage',
    series: 'Sword & Shield',
    year: '2020',
    totalCards: 185,
    secretStart: 186,
    symbol: 'SWSH',
    accentColor: '#eab308',
    rarityRanges: {
      'Common':      [1, 44],
      'Uncommon':    [45, 90],
      'Rare':        [91, 185],
      'Secret Rare': [186, 203],
    },
    rarityTotals: { 'Common': 44, 'Uncommon': 46, 'Rare': 33, 'Rare ex': 36, 'Rare V': 24, 'Rare VMAX': 12, 'Ultra Rare': 20, 'Secret Rare': 18 },
  },
  {
    id: 'swsh5',
    name: 'Battle Styles',
    series: 'Sword & Shield',
    year: '2021',
    totalCards: 163,
    secretStart: 164,
    symbol: 'SWSH',
    accentColor: '#0ea5e9',
    rarityRanges: {
      'Common':      [1, 41],
      'Uncommon':    [42, 87],
      'Rare':        [88, 163],
      'Secret Rare': [164, 183],
    },
    rarityTotals: { 'Common': 41, 'Uncommon': 46, 'Rare': 20, 'Rare ex': 43, 'Rare V': 29, 'Rare VMAX': 14, 'Ultra Rare': 22, 'Secret Rare': 20 },
  },
  {
    id: 'swsh6',
    name: 'Chilling Reign',
    series: 'Sword & Shield',
    year: '2021',
    totalCards: 198,
    secretStart: 199,
    symbol: 'SWSH',
    accentColor: '#06b6d4',
    rarityRanges: {
      'Common':      [1, 43],
      'Uncommon':    [44, 89],
      'Rare':        [90, 198],
      'Secret Rare': [199, 233],
    },
    rarityTotals: { 'Common': 43, 'Uncommon': 46, 'Rare': 23, 'Rare ex': 61, 'Rare V': 42, 'Rare VMAX': 19, 'Ultra Rare': 39, 'Secret Rare': 35 },
  },
  {
    id: 'swsh7',
    name: 'Evolving Skies',
    series: 'Sword & Shield',
    year: '2021',
    totalCards: 203,
    secretStart: 204,
    symbol: 'SWSH',
    accentColor: '#6366f1',
    rarityRanges: {
      'Common':      [1, 42],
      'Uncommon':    [43, 93],
      'Rare':        [94, 203],
      'Secret Rare': [204, 237],
    },
    rarityTotals: { 'Common': 42, 'Uncommon': 51, 'Rare': 19, 'Rare ex': 83, 'Rare V': 51, 'Rare VMAX': 32, 'Ultra Rare': 38, 'Secret Rare': 34 },
  },
  {
    id: 'swsh8',
    name: 'Fusion Strike',
    series: 'Sword & Shield',
    year: '2021',
    totalCards: 264,
    secretStart: 265,
    symbol: 'SWSH',
    accentColor: '#ec4899',
    rarityRanges: {
      'Common':      [1, 89],
      'Uncommon':    [90, 172],
      'Rare':        [173, 264],
      'Secret Rare': [265, 284],
    },
    rarityTotals: { 'Common': 89, 'Uncommon': 83, 'Rare': 32, 'Rare ex': 48, 'Rare V': 32, 'Rare VMAX': 16, 'Ultra Rare': 20, 'Secret Rare': 20 },
  },
  {
    id: 'swsh9',
    name: 'Brilliant Stars',
    series: 'Sword & Shield',
    year: '2022',
    totalCards: 172,
    secretStart: 173,
    symbol: 'SWSH',
    accentColor: '#8b5cf6',
    rarityRanges: {
      'Common':      [1, 42],
      'Uncommon':    [43, 88],
      'Rare':        [89, 172],
      'Secret Rare': [173, 216],
    },
    rarityTotals: { 'Common': 42, 'Uncommon': 46, 'Rare': 38, 'Rare ex': 63, 'Rare V': 44, 'Rare VMAX': 10, 'Rare VSTAR': 9, 'Ultra Rare': 37, 'Secret Rare': 16 },
  },
  {
    id: 'swsh10',
    name: 'Astral Radiance',
    series: 'Sword & Shield',
    year: '2022',
    totalCards: 189,
    secretStart: 190,
    symbol: 'SWSH',
    accentColor: '#0ea5e9',
    rarityRanges: {
      'Common':      [1, 40],
      'Uncommon':    [41, 87],
      'Rare':        [88, 189],
      'Secret Rare': [190, 216],
    },
    rarityTotals: { 'Common': 40, 'Uncommon': 47, 'Rare': 33, 'Holo Rare': 20, 'Radiant Rare': 3, 'Rare ex': 27, 'Rare V': 18, 'Rare VMAX': 2, 'Rare VSTAR': 7, 'Ultra Rare': 47, 'Secret Rare': 29 },
  },
  {
    id: 'swsh11',
    name: 'Lost Origin',
    series: 'Sword & Shield',
    year: '2022',
    totalCards: 196,
    secretStart: 197,
    symbol: 'SWSH',
    accentColor: '#7c3aed',
    rarityRanges: {
      'Common':      [1, 49],
      'Uncommon':    [50, 98],
      'Rare':        [99, 196],
      'Secret Rare': [197, 217],
    },
    rarityTotals: { 'Common': 49, 'Uncommon': 50, 'Rare': 39, 'Holo Rare': 22, 'Radiant Rare': 3, 'Rare ex': 19, 'Rare V': 10, 'Rare VMAX': 3, 'Rare VSTAR': 6, 'Ultra Rare': 42, 'Secret Rare': 23 },
  },
  {
    id: 'swsh12',
    name: 'Silver Tempest',
    series: 'Sword & Shield',
    year: '2022',
    totalCards: 195,
    secretStart: 196,
    symbol: 'SWSH',
    accentColor: '#94a3b8',
    rarityRanges: {
      'Common':      [1, 53],
      'Uncommon':    [54, 109],
      'Rare':        [110, 195],
      'Secret Rare': [196, 215],
    },
    rarityTotals: { 'Common': 53, 'Uncommon': 56, 'Rare': 21, 'Holo Rare': 25, 'Radiant Rare': 3, 'Full Art Trainer': 6, 'Rare ex': 33, 'Rare V': 22, 'Rare VMAX': 5, 'Rare VSTAR': 6, 'Ultra Rare': 26, 'Secret Rare': 22 },
  },
  {
    id: 'sv01',
    name: 'Scarlet & Violet',
    series: 'Scarlet & Violet',
    year: '2023',
    totalCards: 198,
    secretStart: 199,
    symbol: 'SV',
    accentColor: '#ef4444',
    rarityRanges: {
      'Common':      [1, 66],
      'Uncommon':    [67, 127],
      'Rare':        [128, 198],
      'Secret Rare': [199, 258],
    },
    rarityTotals: { 'Common': 66, 'Uncommon': 61, 'Rare': 41, 'Rare ex': 30, 'Ultra Rare': 33, 'Secret Rare': 60 },
  },
  {
    id: 'sv02',
    name: 'Paldea Evolved',
    series: 'Scarlet & Violet',
    year: '2023',
    totalCards: 193,
    secretStart: 194,
    symbol: 'SV',
    accentColor: '#22c55e',
    rarityRanges: {
      'Common':      [1, 81],
      'Uncommon':    [82, 151],
      'Rare':        [152, 193],
      'Secret Rare': [194, 279],
    },
    rarityTotals: { 'Common': 81, 'Uncommon': 70, 'Rare': 25, 'Rare ex': 17, 'Ultra Rare': 26, 'Secret Rare': 86 },
  },
  {
    id: 'sv03',
    name: 'Obsidian Flames',
    series: 'Scarlet & Violet',
    year: '2023',
    totalCards: 197,
    secretStart: 198,
    symbol: 'SV',
    accentColor: '#f97316',
    rarityRanges: {
      'Common':      [1, 92],
      'Uncommon':    [93, 166],
      'Rare':        [167, 197],
      'Secret Rare': [198, 230],
    },
    rarityTotals: { 'Common': 92, 'Uncommon': 74, 'Rare': 10, 'Rare ex': 21, 'Ultra Rare': 12, 'Secret Rare': 33 },
  },
  {
    id: 'sv04',
    name: 'Paradox Rift',
    series: 'Scarlet & Violet',
    year: '2023',
    totalCards: 182,
    secretStart: 183,
    symbol: 'SV',
    accentColor: '#14b8a6',
    rarityRanges: {
      'Common':      [1, 81],
      'Uncommon':    [82, 135],
      'Rare':        [136, 182],
      'Secret Rare': [183, 266],
    },
    rarityTotals: { 'Common': 81, 'Uncommon': 54, 'Rare': 27, 'Rare ex': 20, 'Ultra Rare': 28, 'Secret Rare': 84 },
  },
  {
    id: 'sv05',
    name: 'Temporal Forces',
    series: 'Scarlet & Violet',
    year: '2024',
    totalCards: 162,
    secretStart: 163,
    symbol: 'SV',
    accentColor: '#6366f1',
    rarityRanges: {
      'Common':      [1, 71],
      'Uncommon':    [72, 126],
      'Rare':        [127, 162],
      'Secret Rare': [163, 218],
    },
    rarityTotals: { 'Common': 71, 'Uncommon': 55, 'Rare': 14, 'Rare ex': 15, 'Ultra Rare': 18, 'Secret Rare': 56 },
  },
  {
    id: 'sv06',
    name: 'Twilight Masquerade',
    series: 'Scarlet & Violet',
    year: '2024',
    totalCards: 167,
    secretStart: 168,
    symbol: 'SV',
    accentColor: '#a855f7',
    rarityRanges: {
      'Common':      [1, 76],
      'Uncommon':    [77, 131],
      'Rare':        [132, 167],
      'Secret Rare': [168, 226],
    },
    rarityTotals: { 'Common': 76, 'Uncommon': 55, 'Rare': 16, 'Rare ex': 14, 'Ultra Rare': 21, 'Secret Rare': 59 },
  },
  {
    id: 'sv07',
    name: 'Stellar Crown',
    series: 'Scarlet & Violet',
    year: '2024',
    totalCards: 142,
    secretStart: 143,
    symbol: 'SV',
    accentColor: '#38bdf8',
    rarityRanges: {
      'Common':      [1, 71],
      'Uncommon':    [72, 110],
      'Rare':        [111, 142],
      'Secret Rare': [143, 175],
    },
    rarityTotals: { 'Common': 71, 'Uncommon': 39, 'Rare': 15, 'Rare ex': 14, 'Ultra Rare': 11, 'Secret Rare': 33 },
  },
  {
    id: 'sv08',
    name: 'Surging Sparks',
    series: 'Scarlet & Violet',
    year: '2024',
    totalCards: 191,
    secretStart: 192,
    symbol: 'SV',
    accentColor: '#f59e0b',
    rarityRanges: {
      'Common':      [1, 88],
      'Uncommon':    [89, 149],
      'Rare':        [150, 191],
      'Secret Rare': [192, 252],
    },
    rarityTotals: { 'Common': 88, 'Uncommon': 61, 'Rare': 16, 'Rare ex': 18, 'Ultra Rare': 21, 'Secret Rare': 61 },
  },
  {
    id: 'sv09',
    name: 'Journey Together',
    series: 'Scarlet & Violet',
    year: '2025',
    totalCards: 159,
    secretStart: 160,
    symbol: 'SV',
    accentColor: '#10b981',
    rarityRanges: {
      'Common':      [1, 85],
      'Uncommon':    [86, 127],
      'Rare':        [128, 159],
      'Secret Rare': [160, 190],
    },
    rarityTotals: { 'Common': 85, 'Uncommon': 42, 'Rare': 16, 'Rare ex': 16, 'Ultra Rare': 11, 'Secret Rare': 31 },
  },
  {
    id: 'sv10',
    name: 'Destined Rivals',
    series: 'Scarlet & Violet',
    year: '2025',
    totalCards: 182,
    secretStart: 183,
    symbol: 'SV',
    accentColor: '#ef4444',
    rarityRanges: {
      'Common':      [1, 85],
      'Uncommon':    [86, 147],
      'Rare':        [148, 182],
      'Secret Rare': [183, 244],
    },
    rarityTotals: { 'Common': 85, 'Uncommon': 62, 'Rare': 18, 'Rare ex': 17, 'Ultra Rare': 22, 'Secret Rare': 62 },
  },
  {
    id: 'me01',
    name: 'Mega Evolution',
    series: 'Mega Evolution',
    year: '2025',
    totalCards: 132,
    secretStart: 133,
    symbol: 'ME',
    accentColor: '#f97316',
    rarityRanges: {
      'Common':      [1, 67],
      'Uncommon':    [68, 110],
      'Rare':        [111, 132],
      'Secret Rare': [133, 188],
    },
    rarityTotals: { 'Common': 67, 'Uncommon': 43, 'Rare': 12, 'Rare ex': 10, 'Ultra Rare': 22, 'Secret Rare': 56 },
  },
  {
    id: 'me02',
    name: 'Phantasmal Flames',
    series: 'Mega Evolution',
    year: '2025',
    totalCards: 94,
    secretStart: 95,
    symbol: 'ME',
    accentColor: '#dc2626',
    rarityRanges: {
      'Common':      [1, 43],
      'Uncommon':    [44, 74],
      'Rare':        [75, 94],
      'Secret Rare': [95, 130],
    },
    rarityTotals: { 'Common': 43, 'Uncommon': 31, 'Rare': 10, 'Rare ex': 10, 'Ultra Rare': 17, 'Secret Rare': 36 },
  },
  {
    id: 'me03',
    name: 'Perfect Order',
    series: 'Mega Evolution',
    year: '2026',
    totalCards: 88,
    secretStart: 89,
    symbol: 'ME',
    accentColor: '#2563eb',
    rarityRanges: {
      'Common':      [1, 44],
      'Uncommon':    [45, 68],
      'Rare':        [69, 88],
      'Secret Rare': [89, 124],
    },
    rarityTotals: { 'Common': 44, 'Uncommon': 24, 'Rare': 11, 'Rare ex': 9, 'Ultra Rare': 18, 'Secret Rare': 36 },
  },
];

/** Look up a set definition by its id (e.g. 'base1'). */
export function getSetConfig(id) {
  return SETS.find((s) => s.id === id) ?? null;
}

/**
 * Infer the rarity of a card given its set config and localId.
 *
 * Supports:
 *  - rarityPrefixMap: { 'H': 'Rare Holo' } for non-numeric localIds (e-card H-variants)
 *  - Single range:    [min, max]
 *  - Multi-range:     [[min1, max1], [min2, max2]]  (same rarity in multiple blocks)
 */
export function inferRarity(setConfig, localId) {
  const n = parseInt(localId, 10);
  if (isNaN(n)) {
    // Check prefix map for non-numeric localIds (e.g. H01 in Aquapolis/Skyridge)
    if (setConfig.rarityPrefixMap) {
      for (const [prefix, rarity] of Object.entries(setConfig.rarityPrefixMap)) {
        if (String(localId).startsWith(prefix)) return rarity;
      }
    }
    // H-prefix cards with no explicit mapping are holo variants of regular cards
    // (same art, but with holographic treatment — tracked separately)
    if (/^H/i.test(String(localId))) return 'Holo Variant';
    return 'Common';
  }

  for (const [rarity, ranges] of Object.entries(setConfig.rarityRanges)) {
    // Support both a single [min, max] and an array of ranges [[min,max], ...]
    const rangeList = Array.isArray(ranges[0]) ? ranges : [ranges];
    for (const [min, max] of rangeList) {
      if (n >= min && n <= max) return rarity;
    }
  }
  return 'Common';
}
